# Generated by Django 3.0.9 on 2020-08-20 13:17

from django.db import migrations


def create_columns(apps, schema_editor):
    Column = apps.get_model('cards', 'Column')
    Column.objects.create(id=0)
    Column.objects.create(id=1)
    Column.objects.create(id=2)
    Column.objects.create(id=3)

def reverse(apps, schema_editor):
    Column = apps.get_model('cards', 'Column')
    Column.objects.filter(id=0).delete()
    Column.objects.filter(id=1).delete()
    Column.objects.filter(id=2).delete()
    Column.objects.filter(id=3).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200820_1037'),
    ]

    operations = [
        migrations.RunPython(create_columns, reverse_code=reverse)
    ]
